### ISSUE TITLE
FR: Not only binary sensors

### ISSUE THREAD

**Issue by adamzimnyy** [dylandoamaral/uptime-card#18] opened 2021-03-29 10:53 UTC
Would it be possible to add an option to track not only binary sensors, but by any property of an entity? 

For example, tracking if a light is on by checking "state" property.
or checking if temperature in a room is over or under a set value. 

Right not to do this it requires creating in HA config an extra binary sensor that tracks this property, and passing that into the card. Seems very redundant, especially with a large number of entities.

**Comment by dylandoamaral** [comment] 2021-03-29 11:00
You already can use every kind of sensor. Just use `ok` option to tell to the card which state is considered as `on` such as `connected`, `sunny` etc...

For example, the second card example is not a binary sensor at all.

If you was talking about attributes of a sensor and not states then  it is a duplicate of #2.

**Comment by adamzimnyy** [comment] 2021-03-29 11:51
Ok well, then might just be an UI issue. I cannot select anything other than binary sensors in the configurator: 

![image](https://user-images.githubusercontent.com/14812161/112832439-99cfee80-9095-11eb-858a-0ec957e84d76.png)

**Comment by dylandoamaral** [comment] 2021-03-29 12:00
Yes it is an editor specification I will remove that parts. Originally it was only focused on binary sensors that's why ^^'. I thought nobody used the editor, it is still work in progress (but should be functional). You can still click on the button `EDYTOR YAML` and specify the `entity` option for the moment. It will be fixed for `v0.0.3`.

**Closed** 2021-03-29 18:00 UTC
Labels: editor, question, version 0.0.3
